"""Structured error codes for the POS Integration service."""

from enum import Enum
from typing import Any, Optional

from fastapi import HTTPException, status


class ErrorCode(str, Enum):
    # Transaction errors
    TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
    TRANSACTION_ALREADY_VOIDED = "TRANSACTION_ALREADY_VOIDED"
    TRANSACTION_ALREADY_REFUNDED = "TRANSACTION_ALREADY_REFUNDED"
    TRANSACTION_VOID_NOT_ALLOWED = "TRANSACTION_VOID_NOT_ALLOWED"
    TRANSACTION_INVALID_STATUS = "TRANSACTION_INVALID_STATUS"
    TRANSACTION_INVALID_AMOUNT = "TRANSACTION_INVALID_AMOUNT"
    TRANSACTION_AMOUNT_MISMATCH = "TRANSACTION_AMOUNT_MISMATCH"
    TRANSACTION_ALREADY_FINAL = "TRANSACTION_ALREADY_FINAL"

    # Payment errors
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_ALREADY_REVERSED = "PAYMENT_ALREADY_REVERSED"
    PAYMENT_REVERSE_NOT_ALLOWED = "PAYMENT_REVERSE_NOT_ALLOWED"
    PAYMENT_AMOUNT_MISMATCH = "PAYMENT_AMOUNT_MISMATCH"
    INSUFFICIENT_PAYMENT = "INSUFFICIENT_PAYMENT"

    # Receipt errors
    RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND"
    RECEIPT_GENERATION_FAILED = "RECEIPT_GENERATION_FAILED"

    # Receipt template errors
    RECEIPT_TEMPLATE_NOT_FOUND = "RECEIPT_TEMPLATE_NOT_FOUND"
    RECEIPT_TEMPLATE_NAME_EXISTS = "RECEIPT_TEMPLATE_NAME_EXISTS"

    # Refund errors
    REFUND_NOT_FOUND = "REFUND_NOT_FOUND"
    REFUND_EXCEEDS_ORIGINAL = "REFUND_EXCEEDS_ORIGINAL"
    REFUND_PERIOD_EXPIRED = "REFUND_PERIOD_EXPIRED"
    REFUND_ALREADY_PROCESSED = "REFUND_ALREADY_PROCESSED"

    # Cash drawer errors
    DRAWER_NOT_FOUND = "DRAWER_NOT_FOUND"
    DRAWER_ALREADY_OPEN = "DRAWER_ALREADY_OPEN"
    DRAWER_ALREADY_CLOSED = "DRAWER_ALREADY_CLOSED"
    DRAWER_NOT_OPEN = "DRAWER_NOT_OPEN"
    DRAWER_VARIANCE_EXCEEDED = "DRAWER_VARIANCE_EXCEEDED"

    # Tax errors
    TAX_RATE_NOT_FOUND = "TAX_RATE_NOT_FOUND"
    TAX_RATE_DUPLICATE = "TAX_RATE_DUPLICATE"
    TAX_CALCULATION_FAILED = "TAX_CALCULATION_FAILED"

    # Reconciliation errors
    RECONCILIATION_NOT_FOUND = "RECONCILIATION_NOT_FOUND"
    RECONCILIATION_ALREADY_EXISTS = "RECONCILIATION_ALREADY_EXISTS"
    RECONCILIATION_ALREADY_COMPLETED = "RECONCILIATION_ALREADY_COMPLETED"
    RECONCILIATION_DISCREPANCY = "RECONCILIATION_DISCREPANCY"

    # External POS errors
    INTEGRATION_NOT_FOUND = "INTEGRATION_NOT_FOUND"
    INTEGRATION_ALREADY_EXISTS = "INTEGRATION_ALREADY_EXISTS"
    INTEGRATION_SYNC_FAILED = "INTEGRATION_SYNC_FAILED"
    INTEGRATION_INACTIVE = "INTEGRATION_INACTIVE"

    # Discount errors
    DISCOUNT_NOT_FOUND = "DISCOUNT_NOT_FOUND"
    DISCOUNT_EXPIRED = "DISCOUNT_EXPIRED"
    DISCOUNT_MAX_USES = "DISCOUNT_MAX_USES"
    DISCOUNT_MIN_PURCHASE = "DISCOUNT_MIN_PURCHASE"
    DISCOUNT_MEMBER_REQUIRED = "DISCOUNT_MEMBER_REQUIRED"
    DISCOUNT_NOT_ACTIVE = "DISCOUNT_NOT_ACTIVE"
    DISCOUNT_CODE_EXISTS = "DISCOUNT_CODE_EXISTS"

    # Shift errors
    SHIFT_NOT_FOUND = "SHIFT_NOT_FOUND"
    SHIFT_ALREADY_ACTIVE = "SHIFT_ALREADY_ACTIVE"
    SHIFT_NOT_ACTIVE = "SHIFT_NOT_ACTIVE"
    SHIFT_ALREADY_COMPLETED = "SHIFT_ALREADY_COMPLETED"
    SHIFT_ALREADY_CANCELLED = "SHIFT_ALREADY_CANCELLED"

    # Tip pool errors
    TIP_POOL_NOT_FOUND = "TIP_POOL_NOT_FOUND"
    TIP_POOL_ALREADY_EXISTS = "TIP_POOL_ALREADY_EXISTS"
    TIP_POOL_ALREADY_CLOSED = "TIP_POOL_ALREADY_CLOSED"
    TIP_POOL_ALREADY_DISTRIBUTED = "TIP_POOL_ALREADY_DISTRIBUTED"
    TIP_POOL_NO_PARTICIPANTS = "TIP_POOL_NO_PARTICIPANTS"

    # Currency errors
    CURRENCY_NOT_FOUND = "CURRENCY_NOT_FOUND"
    CURRENCY_CODE_EXISTS = "CURRENCY_CODE_EXISTS"
    CURRENCY_BASE_REQUIRED = "CURRENCY_BASE_REQUIRED"
    CURRENCY_CONVERSION_FAILED = "CURRENCY_CONVERSION_FAILED"

    # Fraud alert errors
    FRAUD_ALERT_NOT_FOUND = "FRAUD_ALERT_NOT_FOUND"

    # General errors
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"


class ServiceError(HTTPException):
    """Structured service error with consistent JSON response."""

    def __init__(
        self,
        error_code: ErrorCode,
        message: str,
        status_code: int = status.HTTP_400_BAD_REQUEST,
        details: Optional[dict[str, Any]] = None,
    ) -> None:
        detail = {"error_code": error_code.value, "message": message}
        if details:
            detail["details"] = details
        super().__init__(status_code=status_code, detail=detail)


def not_found(error_code: ErrorCode, message: str) -> ServiceError:
    return ServiceError(error_code, message, status.HTTP_404_NOT_FOUND)


def conflict(error_code: ErrorCode, message: str, details: Optional[dict] = None) -> ServiceError:
    return ServiceError(error_code, message, status.HTTP_409_CONFLICT, details)


def bad_request(error_code: ErrorCode, message: str, details: Optional[dict] = None) -> ServiceError:
    return ServiceError(error_code, message, status.HTTP_400_BAD_REQUEST, details)
