"""description of changes

Revision ID: e806006bfbda
Revises: 
Create Date: 2026-01-28 16:52:54.077301
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e806006bfbda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_audit_logs',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_audit_actor', 'pos_audit_logs', ['actor_id'], unique=False)
    op.create_index('idx_pos_audit_venue_created', 'pos_audit_logs', ['venue_id', 'created_at'], unique=False)
    op.create_index('idx_pos_audit_venue_entity', 'pos_audit_logs', ['venue_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_pos_audit_logs_actor_id'), 'pos_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_pos_audit_logs_venue_id'), 'pos_audit_logs', ['venue_id'], unique=False)
    op.create_table('pos_currencies',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False, comment='ISO 4217 currency code (e.g., USD, EUR, GBP)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable currency name'),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Currency symbol for display (e.g., $, EUR, GBP)'),
    sa.Column('decimal_places', sa.Integer(), nullable=False, comment='Number of decimal places for this currency'),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=False, comment='Conversion rate to venue base currency'),
    sa.Column('is_base', sa.Boolean(), server_default='false', nullable=False, comment="True if this is the venue's base currency"),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this currency is available for transactions'),
    sa.Column('last_rate_update', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last exchange rate update'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'code', name='uq_pos_currency_venue_code')
    )
    op.create_index('idx_pos_currency_venue_active', 'pos_currencies', ['venue_id', 'is_active'], unique=False)
    op.create_index('idx_pos_currency_venue_base', 'pos_currencies', ['venue_id', 'is_base'], unique=False)
    op.create_index(op.f('ix_pos_currencies_venue_id'), 'pos_currencies', ['venue_id'], unique=False)
    op.create_table('pos_daily_reconciliations',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_tips', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_discounts', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_refunds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('card_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('variance_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reconciled_by', sa.UUID(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'reconciliation_date', name='uq_pos_recon_venue_date')
    )
    op.create_index('idx_pos_recon_venue_date_status', 'pos_daily_reconciliations', ['venue_id', 'reconciliation_date', 'status'], unique=False)
    op.create_index(op.f('ix_pos_daily_reconciliations_venue_id'), 'pos_daily_reconciliations', ['venue_id'], unique=False)
    op.create_table('pos_discounts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_purchase_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('applies_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('requires_member', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_discount_venue_active', 'pos_discounts', ['venue_id', 'is_active'], unique=False)
    op.create_index('idx_pos_discount_venue_code', 'pos_discounts', ['venue_id', 'code'], unique=True)
    op.create_index(op.f('ix_pos_discounts_venue_id'), 'pos_discounts', ['venue_id'], unique=False)
    op.create_table('pos_external_integrations',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('location_id', sa.String(length=100), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('sync_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'provider', name='uq_pos_ext_venue_provider')
    )
    op.create_index('idx_pos_ext_venue_provider_active', 'pos_external_integrations', ['venue_id', 'provider', 'is_active'], unique=False)
    op.create_index(op.f('ix_pos_external_integrations_venue_id'), 'pos_external_integrations', ['venue_id'], unique=False)
    op.create_table('pos_fraud_alerts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detection_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_fraud_alert_venue_created', 'pos_fraud_alerts', ['venue_id', 'created_at'], unique=False)
    op.create_index('idx_pos_fraud_alert_venue_severity', 'pos_fraud_alerts', ['venue_id', 'severity'], unique=False)
    op.create_index('idx_pos_fraud_alert_venue_status', 'pos_fraud_alerts', ['venue_id', 'status'], unique=False)
    op.create_index(op.f('ix_pos_fraud_alerts_venue_id'), 'pos_fraud_alerts', ['venue_id'], unique=False)
    op.create_table('pos_receipt_templates',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('header_logo_url', sa.String(length=500), nullable=True),
    sa.Column('header_text', sa.Text(), nullable=True),
    sa.Column('show_itemized', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_tax_breakdown', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_payment_details', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_cashier_name', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_transaction_id', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_barcode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('barcode_type', sa.String(length=20), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('footer_promo', sa.Text(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_pos_receipt_template_venue_name')
    )
    op.create_index('idx_pos_receipt_template_venue_active', 'pos_receipt_templates', ['venue_id', 'is_active'], unique=False)
    op.create_index('idx_pos_receipt_template_venue_type_default', 'pos_receipt_templates', ['venue_id', 'template_type', 'is_default'], unique=False)
    op.create_index(op.f('ix_pos_receipt_templates_venue_id'), 'pos_receipt_templates', ['venue_id'], unique=False)
    op.create_table('pos_shifts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_shift_venue_employee', 'pos_shifts', ['venue_id', 'employee_id'], unique=False)
    op.create_index('idx_pos_shift_venue_scheduled_start', 'pos_shifts', ['venue_id', 'scheduled_start'], unique=False)
    op.create_index('idx_pos_shift_venue_status', 'pos_shifts', ['venue_id', 'status'], unique=False)
    op.create_index(op.f('ix_pos_shifts_employee_id'), 'pos_shifts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_pos_shifts_venue_id'), 'pos_shifts', ['venue_id'], unique=False)
    op.create_table('pos_tax_rates',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('tax_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('applies_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_tax_venue_effective', 'pos_tax_rates', ['venue_id', 'effective_date'], unique=False)
    op.create_index('idx_pos_tax_venue_type_active', 'pos_tax_rates', ['venue_id', 'tax_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_pos_tax_rates_venue_id'), 'pos_tax_rates', ['venue_id'], unique=False)
    op.create_table('pos_tip_pools',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_tips', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distributed_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pool_participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distribution_method', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distributed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'shift_date', name='uq_pos_tip_pool_venue_date')
    )
    op.create_index('idx_pos_tip_pool_venue_status', 'pos_tip_pools', ['venue_id', 'status'], unique=False)
    op.create_index(op.f('ix_pos_tip_pools_venue_id'), 'pos_tip_pools', ['venue_id'], unique=False)
    op.create_table('pos_transactions',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('cashier_id', sa.UUID(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_txn_venue_created', 'pos_transactions', ['venue_id', 'created_at'], unique=False)
    op.create_index('idx_pos_txn_venue_status', 'pos_transactions', ['venue_id', 'status'], unique=False)
    op.create_index('idx_pos_txn_venue_type', 'pos_transactions', ['venue_id', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_pos_transactions_activity_id'), 'pos_transactions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_pos_transactions_customer_id'), 'pos_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pos_transactions_idempotency_key'), 'pos_transactions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_pos_transactions_venue_id'), 'pos_transactions', ['venue_id'], unique=False)
    op.create_table('pos_cash_drawers',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('terminal_id', sa.String(length=50), nullable=False),
    sa.Column('cashier_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_drops_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('drawer_transactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_drawer_venue_cashier', 'pos_cash_drawers', ['venue_id', 'cashier_id'], unique=False)
    op.create_index('idx_pos_drawer_venue_status', 'pos_cash_drawers', ['venue_id', 'status'], unique=False)
    op.create_index('idx_pos_drawer_venue_terminal_status', 'pos_cash_drawers', ['venue_id', 'terminal_id', 'status'], unique=False)
    op.create_index(op.f('ix_pos_cash_drawers_shift_id'), 'pos_cash_drawers', ['shift_id'], unique=False)
    op.create_index(op.f('ix_pos_cash_drawers_venue_id'), 'pos_cash_drawers', ['venue_id'], unique=False)
    op.create_table('pos_line_items',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_id', sa.UUID(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['pos_discounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_line_item_txn', 'pos_line_items', ['transaction_id'], unique=False)
    op.create_index('idx_pos_line_item_venue_product', 'pos_line_items', ['venue_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_pos_line_items_venue_id'), 'pos_line_items', ['venue_id'], unique=False)
    op.create_table('pos_payments',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_processor', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processor_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('approval_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_pay_processor_txn', 'pos_payments', ['processor_transaction_id'], unique=False)
    op.create_index('idx_pos_pay_txn', 'pos_payments', ['transaction_id'], unique=False)
    op.create_index('idx_pos_pay_venue_status', 'pos_payments', ['venue_id', 'status'], unique=False)
    op.create_index(op.f('ix_pos_payments_venue_id'), 'pos_payments', ['venue_id'], unique=False)
    op.create_table('pos_receipts',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_type', sa.String(length=20), nullable=False),
    sa.Column('receipt_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_to', sa.String(length=255), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index('idx_pos_rcpt_txn', 'pos_receipts', ['transaction_id'], unique=False)
    op.create_index('idx_pos_rcpt_venue_number', 'pos_receipts', ['venue_id', 'receipt_number'], unique=False)
    op.create_index(op.f('ix_pos_receipts_venue_id'), 'pos_receipts', ['venue_id'], unique=False)
    op.create_table('pos_refunds',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refund_reason', sa.String(length=30), nullable=False),
    sa.Column('refund_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processor_refund_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_refund_txn', 'pos_refunds', ['transaction_id'], unique=False)
    op.create_index('idx_pos_refund_venue_created', 'pos_refunds', ['venue_id', 'created_at'], unique=False)
    op.create_index('idx_pos_refund_venue_status', 'pos_refunds', ['venue_id', 'status'], unique=False)
    op.create_index(op.f('ix_pos_refunds_venue_id'), 'pos_refunds', ['venue_id'], unique=False)
    op.create_table('pos_sync_logs',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['pos_external_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_sync_integration_status', 'pos_sync_logs', ['integration_id', 'status'], unique=False)
    op.create_index('idx_pos_sync_venue_started', 'pos_sync_logs', ['venue_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_pos_sync_logs_venue_id'), 'pos_sync_logs', ['venue_id'], unique=False)
    op.create_table('pos_tip_distributions',
    sa.Column('tip_pool_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tip_pool_id'], ['pos_tip_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_tip_dist_pool', 'pos_tip_distributions', ['tip_pool_id'], unique=False)
    op.create_index('idx_pos_tip_dist_venue_created', 'pos_tip_distributions', ['venue_id', 'created_at'], unique=False)
    op.create_index('idx_pos_tip_dist_venue_employee', 'pos_tip_distributions', ['venue_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_pos_tip_distributions_employee_id'), 'pos_tip_distributions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_pos_tip_distributions_venue_id'), 'pos_tip_distributions', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pos_tip_distributions_venue_id'), table_name='pos_tip_distributions')
    op.drop_index(op.f('ix_pos_tip_distributions_employee_id'), table_name='pos_tip_distributions')
    op.drop_index('idx_pos_tip_dist_venue_employee', table_name='pos_tip_distributions')
    op.drop_index('idx_pos_tip_dist_venue_created', table_name='pos_tip_distributions')
    op.drop_index('idx_pos_tip_dist_pool', table_name='pos_tip_distributions')
    op.drop_table('pos_tip_distributions')
    op.drop_index(op.f('ix_pos_sync_logs_venue_id'), table_name='pos_sync_logs')
    op.drop_index('idx_pos_sync_venue_started', table_name='pos_sync_logs')
    op.drop_index('idx_pos_sync_integration_status', table_name='pos_sync_logs')
    op.drop_table('pos_sync_logs')
    op.drop_index(op.f('ix_pos_refunds_venue_id'), table_name='pos_refunds')
    op.drop_index('idx_pos_refund_venue_status', table_name='pos_refunds')
    op.drop_index('idx_pos_refund_venue_created', table_name='pos_refunds')
    op.drop_index('idx_pos_refund_txn', table_name='pos_refunds')
    op.drop_table('pos_refunds')
    op.drop_index(op.f('ix_pos_receipts_venue_id'), table_name='pos_receipts')
    op.drop_index('idx_pos_rcpt_venue_number', table_name='pos_receipts')
    op.drop_index('idx_pos_rcpt_txn', table_name='pos_receipts')
    op.drop_table('pos_receipts')
    op.drop_index(op.f('ix_pos_payments_venue_id'), table_name='pos_payments')
    op.drop_index('idx_pos_pay_venue_status', table_name='pos_payments')
    op.drop_index('idx_pos_pay_txn', table_name='pos_payments')
    op.drop_index('idx_pos_pay_processor_txn', table_name='pos_payments')
    op.drop_table('pos_payments')
    op.drop_index(op.f('ix_pos_line_items_venue_id'), table_name='pos_line_items')
    op.drop_index('idx_pos_line_item_venue_product', table_name='pos_line_items')
    op.drop_index('idx_pos_line_item_txn', table_name='pos_line_items')
    op.drop_table('pos_line_items')
    op.drop_index(op.f('ix_pos_cash_drawers_venue_id'), table_name='pos_cash_drawers')
    op.drop_index(op.f('ix_pos_cash_drawers_shift_id'), table_name='pos_cash_drawers')
    op.drop_index('idx_pos_drawer_venue_terminal_status', table_name='pos_cash_drawers')
    op.drop_index('idx_pos_drawer_venue_status', table_name='pos_cash_drawers')
    op.drop_index('idx_pos_drawer_venue_cashier', table_name='pos_cash_drawers')
    op.drop_table('pos_cash_drawers')
    op.drop_index(op.f('ix_pos_transactions_venue_id'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_idempotency_key'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_customer_id'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_activity_id'), table_name='pos_transactions')
    op.drop_index('idx_pos_txn_venue_type', table_name='pos_transactions')
    op.drop_index('idx_pos_txn_venue_status', table_name='pos_transactions')
    op.drop_index('idx_pos_txn_venue_created', table_name='pos_transactions')
    op.drop_table('pos_transactions')
    op.drop_index(op.f('ix_pos_tip_pools_venue_id'), table_name='pos_tip_pools')
    op.drop_index('idx_pos_tip_pool_venue_status', table_name='pos_tip_pools')
    op.drop_table('pos_tip_pools')
    op.drop_index(op.f('ix_pos_tax_rates_venue_id'), table_name='pos_tax_rates')
    op.drop_index('idx_pos_tax_venue_type_active', table_name='pos_tax_rates')
    op.drop_index('idx_pos_tax_venue_effective', table_name='pos_tax_rates')
    op.drop_table('pos_tax_rates')
    op.drop_index(op.f('ix_pos_shifts_venue_id'), table_name='pos_shifts')
    op.drop_index(op.f('ix_pos_shifts_employee_id'), table_name='pos_shifts')
    op.drop_index('idx_pos_shift_venue_status', table_name='pos_shifts')
    op.drop_index('idx_pos_shift_venue_scheduled_start', table_name='pos_shifts')
    op.drop_index('idx_pos_shift_venue_employee', table_name='pos_shifts')
    op.drop_table('pos_shifts')
    op.drop_index(op.f('ix_pos_receipt_templates_venue_id'), table_name='pos_receipt_templates')
    op.drop_index('idx_pos_receipt_template_venue_type_default', table_name='pos_receipt_templates')
    op.drop_index('idx_pos_receipt_template_venue_active', table_name='pos_receipt_templates')
    op.drop_table('pos_receipt_templates')
    op.drop_index(op.f('ix_pos_fraud_alerts_venue_id'), table_name='pos_fraud_alerts')
    op.drop_index('idx_pos_fraud_alert_venue_status', table_name='pos_fraud_alerts')
    op.drop_index('idx_pos_fraud_alert_venue_severity', table_name='pos_fraud_alerts')
    op.drop_index('idx_pos_fraud_alert_venue_created', table_name='pos_fraud_alerts')
    op.drop_table('pos_fraud_alerts')
    op.drop_index(op.f('ix_pos_external_integrations_venue_id'), table_name='pos_external_integrations')
    op.drop_index('idx_pos_ext_venue_provider_active', table_name='pos_external_integrations')
    op.drop_table('pos_external_integrations')
    op.drop_index(op.f('ix_pos_discounts_venue_id'), table_name='pos_discounts')
    op.drop_index('idx_pos_discount_venue_code', table_name='pos_discounts')
    op.drop_index('idx_pos_discount_venue_active', table_name='pos_discounts')
    op.drop_table('pos_discounts')
    op.drop_index(op.f('ix_pos_daily_reconciliations_venue_id'), table_name='pos_daily_reconciliations')
    op.drop_index('idx_pos_recon_venue_date_status', table_name='pos_daily_reconciliations')
    op.drop_table('pos_daily_reconciliations')
    op.drop_index(op.f('ix_pos_currencies_venue_id'), table_name='pos_currencies')
    op.drop_index('idx_pos_currency_venue_base', table_name='pos_currencies')
    op.drop_index('idx_pos_currency_venue_active', table_name='pos_currencies')
    op.drop_table('pos_currencies')
    op.drop_index(op.f('ix_pos_audit_logs_venue_id'), table_name='pos_audit_logs')
    op.drop_index(op.f('ix_pos_audit_logs_actor_id'), table_name='pos_audit_logs')
    op.drop_index('idx_pos_audit_venue_entity', table_name='pos_audit_logs')
    op.drop_index('idx_pos_audit_venue_created', table_name='pos_audit_logs')
    op.drop_index('idx_pos_audit_actor', table_name='pos_audit_logs')
    op.drop_table('pos_audit_logs')
    # ### end Alembic commands ###
