"""
=============================================================================
FILE: services/fraud_detection_service.py
PURPOSE: Advanced fraud detection service for the POS Integration Service
=============================================================================

Provides comprehensive fraud detection capabilities for point-of-sale operations.
This service implements multiple detection strategies to identify suspicious activity
including:

- High void rates by cashier
- Unusual refund patterns
- After-hours transactions
- Large discounts exceeding thresholds
- Excessive complimentary transactions
- Cash drawer variance analysis
- Split transaction detection (structuring)
- Repeated void patterns

The service supports:
- Real-time fraud checks on individual transactions
- Batch analysis for daily fraud reports
- Alert management and investigation workflow
- Event publishing for alert notifications

Detection rules are configurable via FraudRule dataclass and can be extended
to support venue-specific thresholds.
"""

import uuid
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple

import structlog
from sqlalchemy import and_, case, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.errors import ErrorCode, not_found
from app.models.pos import (
    CashDrawer,
    CashDrawerStatus,
    FraudAlert,
    FraudAlertSeverity,
    FraudAlertStatus,
    Payment,
    PaymentMethod,
    PaymentStatus,
    Refund,
    RefundStatus,
    Transaction,
    TransactionStatus,
)
from app.services.event_publisher import EventPublisher, EventType

logger = structlog.get_logger()


@dataclass
class FraudRule:
    """
    Configuration for a fraud detection rule.

    Attributes:
        name: Unique identifier for the rule (e.g., "high_void_rate").
        description: Human-readable description of what the rule detects.
        check_function: Name of the method to call for this check.
        severity: Default severity level for alerts generated by this rule.
        threshold: Default threshold value for triggering the rule.
    """
    name: str
    description: str
    check_function: str
    severity: FraudAlertSeverity
    threshold: float


# Default fraud detection rules
DEFAULT_FRAUD_RULES: List[FraudRule] = [
    FraudRule(
        name="high_void_rate",
        description="Detects cashiers with void rates exceeding threshold",
        check_function="check_high_void_rate",
        severity=FraudAlertSeverity.HIGH,
        threshold=0.1,
    ),
    FraudRule(
        name="unusual_refunds",
        description="Detects unusual refund patterns by cashier",
        check_function="check_unusual_refund_pattern",
        severity=FraudAlertSeverity.MEDIUM,
        threshold=5.0,
    ),
    FraudRule(
        name="after_hours",
        description="Detects transactions outside business hours",
        check_function="check_after_hours_transaction",
        severity=FraudAlertSeverity.LOW,
        threshold=0.0,
    ),
    FraudRule(
        name="large_discount",
        description="Detects transactions with large discounts",
        check_function="check_large_discount",
        severity=FraudAlertSeverity.MEDIUM,
        threshold=50.0,
    ),
    FraudRule(
        name="excessive_comps",
        description="Detects excessive complimentary transactions",
        check_function="check_excessive_comps",
        severity=FraudAlertSeverity.HIGH,
        threshold=3.0,
    ),
    FraudRule(
        name="cash_drawer_variance",
        description="Detects significant cash drawer variances",
        check_function="check_cash_drawer_variance",
        severity=FraudAlertSeverity.HIGH,
        threshold=20.0,
    ),
    FraudRule(
        name="split_transactions",
        description="Detects potential transaction structuring",
        check_function="check_split_transactions",
        severity=FraudAlertSeverity.CRITICAL,
        threshold=100.0,
    ),
    FraudRule(
        name="repeated_voids",
        description="Detects repeated void patterns",
        check_function="check_repeated_voids",
        severity=FraudAlertSeverity.MEDIUM,
        threshold=3.0,
    ),
]


class FraudDetectionService:
    """
    Service for detecting and managing fraud alerts in POS operations.

    This service provides comprehensive fraud detection capabilities including
    real-time transaction analysis, batch processing for daily reports, and
    alert lifecycle management.

    Attributes:
        db: AsyncSession for database operations.
        event_publisher: Optional EventPublisher for sending alert notifications.
        rules: List of FraudRule configurations for detection.
    """

    def __init__(
        self,
        db: AsyncSession,
        event_publisher: Optional[EventPublisher] = None,
        rules: Optional[List[FraudRule]] = None,
    ) -> None:
        """
        Initialize the fraud detection service.

        Args:
            db: SQLAlchemy async session for database operations.
            event_publisher: Optional publisher for fraud alert events.
            rules: Optional list of custom fraud rules. Defaults to DEFAULT_FRAUD_RULES.
        """
        self.db = db
        self.event_publisher = event_publisher
        self.rules = rules or DEFAULT_FRAUD_RULES

    # =========================================================================
    # Alert Management
    # =========================================================================

    async def get_alert(self, alert_id: uuid.UUID) -> FraudAlert:
        """
        Retrieve a fraud alert by ID.

        Args:
            alert_id: The UUID of the fraud alert to retrieve.

        Returns:
            The FraudAlert instance.

        Raises:
            ServiceError: If the alert is not found (FRAUD_ALERT_NOT_FOUND).
        """
        result = await self.db.execute(
            select(FraudAlert).where(FraudAlert.id == alert_id)
        )
        alert = result.scalars().first()
        if not alert:
            raise not_found(
                ErrorCode.FRAUD_ALERT_NOT_FOUND,
                f"Fraud alert {alert_id} not found",
            )
        return alert

    async def list_alerts(
        self,
        venue_id: uuid.UUID,
        status: Optional[FraudAlertStatus] = None,
        severity: Optional[FraudAlertSeverity] = None,
        date_from: Optional[date] = None,
        date_to: Optional[date] = None,
        skip: int = 0,
        limit: int = 50,
    ) -> List[FraudAlert]:
        """
        List fraud alerts for a venue with optional filtering.

        Args:
            venue_id: The venue to list alerts for.
            status: Optional filter by alert status.
            severity: Optional filter by alert severity.
            date_from: Optional start date filter (inclusive).
            date_to: Optional end date filter (inclusive).
            skip: Number of records to skip for pagination.
            limit: Maximum number of records to return.

        Returns:
            List of FraudAlert instances matching the criteria.
        """
        query = select(FraudAlert).where(FraudAlert.venue_id == venue_id)

        if status:
            query = query.where(FraudAlert.status == status.value)
        if severity:
            query = query.where(FraudAlert.severity == severity.value)
        if date_from:
            query = query.where(
                func.date(FraudAlert.created_at) >= date_from
            )
        if date_to:
            query = query.where(
                func.date(FraudAlert.created_at) <= date_to
            )

        query = query.order_by(FraudAlert.created_at.desc())
        query = query.offset(skip).limit(limit)

        result = await self.db.execute(query)
        alerts = list(result.scalars().all())

        logger.info(
            "fraud_alerts_listed",
            venue_id=str(venue_id),
            count=len(alerts),
            status=status.value if status else None,
            severity=severity.value if severity else None,
        )

        return alerts

    async def update_alert_status(
        self,
        alert_id: uuid.UUID,
        status: FraudAlertStatus,
        notes: Optional[str] = None,
        resolved_by: Optional[uuid.UUID] = None,
    ) -> FraudAlert:
        """
        Update the status of a fraud alert.

        Handles status transitions and resolution tracking. When resolving
        an alert, the resolved_at timestamp and resolved_by user are recorded.
        Publishes FRAUD_ALERT_RESOLVED event when an alert is resolved.

        Args:
            alert_id: The UUID of the alert to update.
            status: The new status to set.
            notes: Optional resolution or investigation notes.
            resolved_by: UUID of the user resolving the alert (required for RESOLVED status).

        Returns:
            The updated FraudAlert instance.

        Raises:
            ServiceError: If the alert is not found.
        """
        alert = await self.get_alert(alert_id)
        old_status = alert.status
        previous_severity = alert.severity

        alert.status = status.value

        if notes:
            alert.resolution_notes = notes

        # Handle resolution
        if status in (FraudAlertStatus.RESOLVED, FraudAlertStatus.DISMISSED):
            alert.resolved_at = datetime.utcnow()
            if resolved_by:
                alert.resolved_by = resolved_by

        await self.db.commit()
        await self.db.refresh(alert)

        logger.info(
            "fraud_alert_status_updated",
            alert_id=str(alert_id),
            venue_id=str(alert.venue_id),
            old_status=old_status,
            new_status=status.value,
        )

        # Publish resolution event
        if self.event_publisher and status in (
            FraudAlertStatus.RESOLVED,
            FraudAlertStatus.DISMISSED,
        ):
            await self.event_publisher.publish(
                EventType.FRAUD_ALERT_RESOLVED,
                {
                    "alert_id": str(alert.id),
                    "venue_id": str(alert.venue_id),
                    "alert_type": alert.alert_type,
                    "severity": alert.severity,
                    "status": status.value,
                    "resolved_by": str(resolved_by) if resolved_by else None,
                },
                venue_id=alert.venue_id,
            )

        # Publish escalation event if severity indicates escalation
        if self.event_publisher and status == FraudAlertStatus.CONFIRMED:
            await self.event_publisher.publish(
                EventType.FRAUD_ALERT_ESCALATED,
                {
                    "alert_id": str(alert.id),
                    "venue_id": str(alert.venue_id),
                    "alert_type": alert.alert_type,
                    "severity": alert.severity,
                    "previous_status": old_status,
                    "new_status": status.value,
                },
                venue_id=alert.venue_id,
            )

        return alert

    async def assign_alert(
        self,
        alert_id: uuid.UUID,
        assigned_to: uuid.UUID,
    ) -> FraudAlert:
        """
        Assign a fraud alert to a user for investigation.

        Args:
            alert_id: The UUID of the alert to assign.
            assigned_to: The UUID of the user to assign the alert to.

        Returns:
            The updated FraudAlert instance.

        Raises:
            ServiceError: If the alert is not found.
        """
        alert = await self.get_alert(alert_id)

        alert.assigned_to = assigned_to
        # Auto-transition to investigating when assigned
        if alert.status == FraudAlertStatus.NEW.value:
            alert.status = FraudAlertStatus.INVESTIGATING.value

        await self.db.commit()
        await self.db.refresh(alert)

        logger.info(
            "fraud_alert_assigned",
            alert_id=str(alert_id),
            venue_id=str(alert.venue_id),
            assigned_to=str(assigned_to),
        )

        return alert

    # =========================================================================
    # Detection Checks
    # =========================================================================

    async def check_high_void_rate(
        self,
        venue_id: uuid.UUID,
        cashier_id: uuid.UUID,
        threshold: float = 0.1,
    ) -> Optional[FraudAlert]:
        """
        Check if a cashier has a high void rate.

        Calculates the ratio of voided transactions to total transactions
        for the cashier and creates an alert if the rate exceeds the threshold.

        Args:
            venue_id: The venue to check.
            cashier_id: The cashier to analyze.
            threshold: Maximum acceptable void rate (default 0.1 = 10%).

        Returns:
            FraudAlert if threshold exceeded, None otherwise.
        """
        # Get transaction counts for the cashier in the last 24 hours
        since = datetime.utcnow() - timedelta(hours=24)

        total_query = select(func.count(Transaction.id)).where(
            and_(
                Transaction.venue_id == venue_id,
                Transaction.cashier_id == cashier_id,
                Transaction.created_at >= since,
            )
        )
        total_result = await self.db.execute(total_query)
        total_transactions = total_result.scalar() or 0

        if total_transactions < 10:
            # Not enough data to determine void rate
            return None

        voided_query = select(func.count(Transaction.id)).where(
            and_(
                Transaction.venue_id == venue_id,
                Transaction.cashier_id == cashier_id,
                Transaction.created_at >= since,
                Transaction.status == TransactionStatus.VOIDED.value,
            )
        )
        voided_result = await self.db.execute(voided_query)
        voided_transactions = voided_result.scalar() or 0

        void_rate = voided_transactions / total_transactions

        if void_rate > threshold:
            logger.warning(
                "high_void_rate_detected",
                venue_id=str(venue_id),
                cashier_id=str(cashier_id),
                void_rate=void_rate,
                threshold=threshold,
            )

            return await self._create_alert(
                venue_id=venue_id,
                alert_type="high_void_rate",
                severity=FraudAlertSeverity.HIGH,
                title=f"High void rate detected: {void_rate:.1%}",
                description=(
                    f"Cashier has a void rate of {void_rate:.1%} "
                    f"({voided_transactions} voided out of {total_transactions} transactions) "
                    f"in the last 24 hours, exceeding the threshold of {threshold:.1%}."
                ),
                detection_data={
                    "total_transactions": total_transactions,
                    "voided_transactions": voided_transactions,
                    "void_rate": float(void_rate),
                    "period_hours": 24,
                },
                entity_type="cashier",
                entity_id=cashier_id,
                threshold_value=Decimal(str(threshold)),
                actual_value=Decimal(str(void_rate)),
            )

        return None

    async def check_unusual_refund_pattern(
        self,
        venue_id: uuid.UUID,
        cashier_id: uuid.UUID,
        hours: int = 24,
        threshold: int = 5,
    ) -> Optional[FraudAlert]:
        """
        Check for unusual refund patterns by a cashier.

        Analyzes refund frequency and amounts to detect suspicious patterns
        that may indicate fraudulent activity.

        Args:
            venue_id: The venue to check.
            cashier_id: The cashier to analyze.
            hours: Time window to analyze (default 24 hours).
            threshold: Maximum number of refunds before alert (default 5).

        Returns:
            FraudAlert if unusual pattern detected, None otherwise.
        """
        since = datetime.utcnow() - timedelta(hours=hours)

        # Count refunds processed by this cashier (via transaction)
        refund_query = (
            select(
                func.count(Refund.id).label("refund_count"),
                func.coalesce(func.sum(Refund.refund_amount), Decimal("0")).label("total_amount"),
            )
            .select_from(Refund)
            .join(Transaction, Transaction.id == Refund.transaction_id)
            .where(
                and_(
                    Transaction.venue_id == venue_id,
                    Transaction.cashier_id == cashier_id,
                    Refund.created_at >= since,
                    Refund.status.in_([
                        RefundStatus.APPROVED.value,
                        RefundStatus.PROCESSED.value,
                    ]),
                )
            )
        )

        result = await self.db.execute(refund_query)
        row = result.one()
        refund_count = row.refund_count or 0
        total_amount = row.total_amount or Decimal("0")

        if refund_count > threshold:
            logger.warning(
                "unusual_refund_pattern_detected",
                venue_id=str(venue_id),
                cashier_id=str(cashier_id),
                refund_count=refund_count,
                total_amount=str(total_amount),
                threshold=threshold,
            )

            return await self._create_alert(
                venue_id=venue_id,
                alert_type="unusual_refunds",
                severity=FraudAlertSeverity.MEDIUM,
                title=f"Unusual refund pattern: {refund_count} refunds",
                description=(
                    f"Cashier has processed {refund_count} refunds totaling ${total_amount:.2f} "
                    f"in the last {hours} hours, exceeding the threshold of {threshold} refunds."
                ),
                detection_data={
                    "refund_count": refund_count,
                    "total_amount": str(total_amount),
                    "period_hours": hours,
                },
                entity_type="cashier",
                entity_id=cashier_id,
                threshold_value=Decimal(str(threshold)),
                actual_value=Decimal(str(refund_count)),
            )

        return None

    async def check_after_hours_transaction(
        self,
        venue_id: uuid.UUID,
        transaction_id: uuid.UUID,
        business_hours: Tuple[int, int] = (9, 22),
    ) -> Optional[FraudAlert]:
        """
        Check if a transaction occurred outside business hours.

        Args:
            venue_id: The venue to check.
            transaction_id: The transaction to analyze.
            business_hours: Tuple of (start_hour, end_hour) in 24-hour format.
                           Default is 9 AM to 10 PM.

        Returns:
            FraudAlert if transaction is outside business hours, None otherwise.
        """
        result = await self.db.execute(
            select(Transaction).where(Transaction.id == transaction_id)
        )
        transaction = result.scalars().first()

        if not transaction:
            return None

        transaction_hour = transaction.created_at.hour
        start_hour, end_hour = business_hours

        if transaction_hour < start_hour or transaction_hour >= end_hour:
            logger.warning(
                "after_hours_transaction_detected",
                venue_id=str(venue_id),
                transaction_id=str(transaction_id),
                transaction_hour=transaction_hour,
                business_hours=business_hours,
            )

            return await self._create_alert(
                venue_id=venue_id,
                alert_type="after_hours",
                severity=FraudAlertSeverity.LOW,
                title=f"After-hours transaction at {transaction_hour}:00",
                description=(
                    f"Transaction occurred at {transaction.created_at.strftime('%H:%M')} "
                    f"which is outside business hours ({start_hour}:00 - {end_hour}:00). "
                    f"Amount: ${transaction.total_amount:.2f}"
                ),
                detection_data={
                    "transaction_hour": transaction_hour,
                    "business_hours_start": start_hour,
                    "business_hours_end": end_hour,
                    "transaction_time": transaction.created_at.isoformat(),
                    "amount": str(transaction.total_amount),
                },
                entity_type="transaction",
                entity_id=transaction_id,
            )

        return None

    async def check_large_discount(
        self,
        venue_id: uuid.UUID,
        transaction_id: uuid.UUID,
        discount_threshold_percent: float = 50,
    ) -> Optional[FraudAlert]:
        """
        Check if a transaction has an unusually large discount.

        Args:
            venue_id: The venue to check.
            transaction_id: The transaction to analyze.
            discount_threshold_percent: Maximum acceptable discount percentage.
                                       Default is 50%.

        Returns:
            FraudAlert if discount exceeds threshold, None otherwise.
        """
        result = await self.db.execute(
            select(Transaction).where(Transaction.id == transaction_id)
        )
        transaction = result.scalars().first()

        if not transaction or transaction.subtotal == 0:
            return None

        discount_percent = (
            float(transaction.discount_amount) / float(transaction.subtotal)
        ) * 100

        if discount_percent > discount_threshold_percent:
            logger.warning(
                "large_discount_detected",
                venue_id=str(venue_id),
                transaction_id=str(transaction_id),
                discount_percent=discount_percent,
                threshold=discount_threshold_percent,
            )

            return await self._create_alert(
                venue_id=venue_id,
                alert_type="large_discount",
                severity=FraudAlertSeverity.MEDIUM,
                title=f"Large discount applied: {discount_percent:.1f}%",
                description=(
                    f"Transaction has a discount of ${transaction.discount_amount:.2f} "
                    f"({discount_percent:.1f}%) on a subtotal of ${transaction.subtotal:.2f}, "
                    f"exceeding the threshold of {discount_threshold_percent}%."
                ),
                detection_data={
                    "subtotal": str(transaction.subtotal),
                    "discount_amount": str(transaction.discount_amount),
                    "discount_percent": discount_percent,
                    "cashier_id": str(transaction.cashier_id) if transaction.cashier_id else None,
                },
                entity_type="transaction",
                entity_id=transaction_id,
                threshold_value=Decimal(str(discount_threshold_percent)),
                actual_value=Decimal(str(discount_percent)),
            )

        return None

    async def check_excessive_comps(
        self,
        venue_id: uuid.UUID,
        cashier_id: uuid.UUID,
        hours: int = 8,
        threshold: int = 3,
    ) -> Optional[FraudAlert]:
        """
        Check for excessive complimentary (comp) transactions by a cashier.

        Args:
            venue_id: The venue to check.
            cashier_id: The cashier to analyze.
            hours: Time window to analyze (default 8 hours / one shift).
            threshold: Maximum number of comps before alert (default 3).

        Returns:
            FraudAlert if excessive comps detected, None otherwise.
        """
        since = datetime.utcnow() - timedelta(hours=hours)

        # Count comp payments processed by this cashier
        comp_query = (
            select(
                func.count(Payment.id).label("comp_count"),
                func.coalesce(func.sum(Payment.amount), Decimal("0")).label("total_amount"),
            )
            .select_from(Payment)
            .join(Transaction, Transaction.id == Payment.transaction_id)
            .where(
                and_(
                    Transaction.venue_id == venue_id,
                    Transaction.cashier_id == cashier_id,
                    Payment.created_at >= since,
                    Payment.payment_method == PaymentMethod.COMP.value,
                    Payment.status == PaymentStatus.COMPLETED.value,
                )
            )
        )

        result = await self.db.execute(comp_query)
        row = result.one()
        comp_count = row.comp_count or 0
        total_amount = row.total_amount or Decimal("0")

        if comp_count > threshold:
            logger.warning(
                "excessive_comps_detected",
                venue_id=str(venue_id),
                cashier_id=str(cashier_id),
                comp_count=comp_count,
                total_amount=str(total_amount),
                threshold=threshold,
            )

            return await self._create_alert(
                venue_id=venue_id,
                alert_type="excessive_comps",
                severity=FraudAlertSeverity.HIGH,
                title=f"Excessive comps: {comp_count} complimentary transactions",
                description=(
                    f"Cashier has processed {comp_count} complimentary transactions "
                    f"totaling ${total_amount:.2f} in the last {hours} hours, "
                    f"exceeding the threshold of {threshold}."
                ),
                detection_data={
                    "comp_count": comp_count,
                    "total_amount": str(total_amount),
                    "period_hours": hours,
                },
                entity_type="cashier",
                entity_id=cashier_id,
                threshold_value=Decimal(str(threshold)),
                actual_value=Decimal(str(comp_count)),
            )

        return None

    async def check_cash_drawer_variance(
        self,
        venue_id: uuid.UUID,
        drawer_id: uuid.UUID,
        threshold: Decimal = Decimal("20.00"),
    ) -> Optional[FraudAlert]:
        """
        Check if a cash drawer has a significant variance.

        Args:
            venue_id: The venue to check.
            drawer_id: The cash drawer to analyze.
            threshold: Maximum acceptable variance amount (default $20).

        Returns:
            FraudAlert if variance exceeds threshold, None otherwise.
        """
        result = await self.db.execute(
            select(CashDrawer).where(CashDrawer.id == drawer_id)
        )
        drawer = result.scalars().first()

        if not drawer or drawer.variance is None:
            return None

        variance_abs = abs(drawer.variance)

        if variance_abs > threshold:
            variance_type = "shortage" if drawer.variance < 0 else "overage"

            logger.warning(
                "cash_drawer_variance_detected",
                venue_id=str(venue_id),
                drawer_id=str(drawer_id),
                variance=str(drawer.variance),
                threshold=str(threshold),
            )

            return await self._create_alert(
                venue_id=venue_id,
                alert_type="cash_drawer_variance",
                severity=FraudAlertSeverity.HIGH,
                title=f"Cash drawer {variance_type}: ${variance_abs:.2f}",
                description=(
                    f"Cash drawer has a {variance_type} of ${variance_abs:.2f}. "
                    f"Expected: ${drawer.expected_cash:.2f}, "
                    f"Actual: ${drawer.closing_cash:.2f}. "
                    f"Terminal: {drawer.terminal_id}"
                ),
                detection_data={
                    "opening_cash": str(drawer.opening_cash),
                    "expected_cash": str(drawer.expected_cash),
                    "closing_cash": str(drawer.closing_cash),
                    "variance": str(drawer.variance),
                    "variance_type": variance_type,
                    "terminal_id": drawer.terminal_id,
                    "cashier_id": str(drawer.cashier_id),
                },
                entity_type="terminal",
                entity_id=drawer_id,
                threshold_value=threshold,
                actual_value=variance_abs,
            )

        return None

    async def check_split_transactions(
        self,
        venue_id: uuid.UUID,
        time_window_minutes: int = 5,
        amount_threshold: Decimal = Decimal("100"),
    ) -> List[FraudAlert]:
        """
        Check for potential split transaction patterns (structuring).

        Detects multiple smaller transactions that may be intentionally
        split to avoid thresholds or oversight.

        Args:
            venue_id: The venue to check.
            time_window_minutes: Time window to group transactions.
            amount_threshold: Minimum combined amount to trigger alert.

        Returns:
            List of FraudAlerts for detected split patterns.
        """
        # Look at transactions in the last 24 hours
        since = datetime.utcnow() - timedelta(hours=24)
        alerts: List[FraudAlert] = []

        # Find cashiers with multiple transactions close together
        # This is a simplified check - production might use more sophisticated analysis
        subquery = (
            select(
                Transaction.cashier_id,
                Transaction.customer_id,
                func.count(Transaction.id).label("txn_count"),
                func.sum(Transaction.total_amount).label("total_amount"),
            )
            .where(
                and_(
                    Transaction.venue_id == venue_id,
                    Transaction.created_at >= since,
                    Transaction.status == TransactionStatus.COMPLETED.value,
                    Transaction.cashier_id.isnot(None),
                )
            )
            .group_by(
                Transaction.cashier_id,
                Transaction.customer_id,
                func.date_trunc("hour", Transaction.created_at),
            )
            .having(
                and_(
                    func.count(Transaction.id) >= 3,
                    func.sum(Transaction.total_amount) >= amount_threshold,
                )
            )
        )

        result = await self.db.execute(subquery)
        suspicious_patterns = result.fetchall()

        for pattern in suspicious_patterns:
            cashier_id = pattern.cashier_id
            customer_id = pattern.customer_id
            txn_count = pattern.txn_count
            total_amount = pattern.total_amount

            logger.warning(
                "split_transactions_detected",
                venue_id=str(venue_id),
                cashier_id=str(cashier_id) if cashier_id else None,
                customer_id=str(customer_id) if customer_id else None,
                txn_count=txn_count,
                total_amount=str(total_amount),
            )

            alert = await self._create_alert(
                venue_id=venue_id,
                alert_type="split_transactions",
                severity=FraudAlertSeverity.CRITICAL,
                title=f"Potential split transactions: {txn_count} transactions",
                description=(
                    f"Detected {txn_count} transactions totaling ${total_amount:.2f} "
                    f"within a short time period, which may indicate transaction structuring. "
                    f"Customer: {customer_id if customer_id else 'Unknown'}"
                ),
                detection_data={
                    "transaction_count": txn_count,
                    "total_amount": str(total_amount),
                    "time_window_minutes": time_window_minutes,
                    "customer_id": str(customer_id) if customer_id else None,
                },
                entity_type="cashier",
                entity_id=cashier_id,
                threshold_value=amount_threshold,
                actual_value=total_amount,
            )
            alerts.append(alert)

        return alerts

    async def check_repeated_voids(
        self,
        venue_id: uuid.UUID,
        cashier_id: uuid.UUID,
        hours: int = 4,
        threshold: int = 3,
    ) -> Optional[FraudAlert]:
        """
        Check for repeated void patterns by a cashier within a short period.

        Args:
            venue_id: The venue to check.
            cashier_id: The cashier to analyze.
            hours: Time window to analyze (default 4 hours).
            threshold: Maximum number of voids before alert (default 3).

        Returns:
            FraudAlert if repeated voids detected, None otherwise.
        """
        since = datetime.utcnow() - timedelta(hours=hours)

        void_query = select(
            func.count(Transaction.id).label("void_count"),
            func.coalesce(func.sum(Transaction.total_amount), Decimal("0")).label("total_amount"),
        ).where(
            and_(
                Transaction.venue_id == venue_id,
                Transaction.cashier_id == cashier_id,
                Transaction.created_at >= since,
                Transaction.status == TransactionStatus.VOIDED.value,
            )
        )

        result = await self.db.execute(void_query)
        row = result.one()
        void_count = row.void_count or 0
        total_amount = row.total_amount or Decimal("0")

        if void_count >= threshold:
            logger.warning(
                "repeated_voids_detected",
                venue_id=str(venue_id),
                cashier_id=str(cashier_id),
                void_count=void_count,
                total_amount=str(total_amount),
                threshold=threshold,
            )

            return await self._create_alert(
                venue_id=venue_id,
                alert_type="repeated_voids",
                severity=FraudAlertSeverity.MEDIUM,
                title=f"Repeated voids: {void_count} in {hours} hours",
                description=(
                    f"Cashier has voided {void_count} transactions "
                    f"totaling ${total_amount:.2f} in the last {hours} hours, "
                    f"which exceeds the threshold of {threshold}."
                ),
                detection_data={
                    "void_count": void_count,
                    "total_amount": str(total_amount),
                    "period_hours": hours,
                },
                entity_type="cashier",
                entity_id=cashier_id,
                threshold_value=Decimal(str(threshold)),
                actual_value=Decimal(str(void_count)),
            )

        return None

    # =========================================================================
    # Batch Analysis
    # =========================================================================

    async def run_daily_fraud_analysis(
        self,
        venue_id: uuid.UUID,
        target_date: date,
    ) -> List[FraudAlert]:
        """
        Run comprehensive fraud analysis for a specific date.

        Executes all fraud detection rules and generates alerts for any
        suspicious activity detected. This is typically run as a batch
        job at the end of each business day.

        Args:
            venue_id: The venue to analyze.
            target_date: The date to analyze.

        Returns:
            List of FraudAlerts generated during analysis.
        """
        logger.info(
            "daily_fraud_analysis_started",
            venue_id=str(venue_id),
            target_date=str(target_date),
        )

        alerts: List[FraudAlert] = []

        # Get all cashiers who worked on this date
        cashier_query = (
            select(Transaction.cashier_id)
            .where(
                and_(
                    Transaction.venue_id == venue_id,
                    func.date(Transaction.created_at) == target_date,
                    Transaction.cashier_id.isnot(None),
                )
            )
            .distinct()
        )

        result = await self.db.execute(cashier_query)
        cashier_ids = [row[0] for row in result.fetchall()]

        # Run cashier-specific checks
        for cashier_id in cashier_ids:
            # High void rate
            alert = await self.check_high_void_rate(venue_id, cashier_id)
            if alert:
                alerts.append(alert)

            # Unusual refund patterns
            alert = await self.check_unusual_refund_pattern(venue_id, cashier_id)
            if alert:
                alerts.append(alert)

            # Excessive comps
            alert = await self.check_excessive_comps(venue_id, cashier_id)
            if alert:
                alerts.append(alert)

            # Repeated voids
            alert = await self.check_repeated_voids(venue_id, cashier_id)
            if alert:
                alerts.append(alert)

        # Check cash drawers closed on this date
        drawer_query = select(CashDrawer).where(
            and_(
                CashDrawer.venue_id == venue_id,
                func.date(CashDrawer.closed_at) == target_date,
                CashDrawer.status == CashDrawerStatus.CLOSED.value,
            )
        )

        drawer_result = await self.db.execute(drawer_query)
        drawers = drawer_result.scalars().all()

        for drawer in drawers:
            alert = await self.check_cash_drawer_variance(venue_id, drawer.id)
            if alert:
                alerts.append(alert)

        # Check for split transactions
        split_alerts = await self.check_split_transactions(venue_id)
        alerts.extend(split_alerts)

        logger.info(
            "daily_fraud_analysis_completed",
            venue_id=str(venue_id),
            target_date=str(target_date),
            alerts_generated=len(alerts),
        )

        return alerts

    async def get_fraud_summary(
        self,
        venue_id: uuid.UUID,
        date_from: date,
        date_to: date,
    ) -> Dict[str, Any]:
        """
        Generate a fraud alert summary for a date range.

        Provides aggregate statistics on fraud alerts including counts
        by status, severity, and type, as well as resolution metrics.

        Args:
            venue_id: The venue to summarize.
            date_from: Start date (inclusive).
            date_to: End date (inclusive).

        Returns:
            Dictionary containing summary statistics.
        """
        base_filter = and_(
            FraudAlert.venue_id == venue_id,
            func.date(FraudAlert.created_at) >= date_from,
            func.date(FraudAlert.created_at) <= date_to,
        )

        # Total count
        total_query = select(func.count(FraudAlert.id)).where(base_filter)
        total_result = await self.db.execute(total_query)
        total_alerts = total_result.scalar() or 0

        # Counts by status
        status_query = (
            select(
                FraudAlert.status,
                func.count(FraudAlert.id).label("count"),
            )
            .where(base_filter)
            .group_by(FraudAlert.status)
        )
        status_result = await self.db.execute(status_query)
        by_status = {row.status: row.count for row in status_result.fetchall()}

        # Counts by severity
        severity_query = (
            select(
                FraudAlert.severity,
                func.count(FraudAlert.id).label("count"),
            )
            .where(base_filter)
            .group_by(FraudAlert.severity)
        )
        severity_result = await self.db.execute(severity_query)
        by_severity = {row.severity: row.count for row in severity_result.fetchall()}

        # Counts by type
        type_query = (
            select(
                FraudAlert.alert_type,
                func.count(FraudAlert.id).label("count"),
            )
            .where(base_filter)
            .group_by(FraudAlert.alert_type)
        )
        type_result = await self.db.execute(type_query)
        by_type = {row.alert_type: row.count for row in type_result.fetchall()}

        # Unresolved critical/high alerts
        unresolved_statuses = [
            FraudAlertStatus.NEW.value,
            FraudAlertStatus.INVESTIGATING.value,
        ]

        critical_unresolved_query = select(func.count(FraudAlert.id)).where(
            and_(
                base_filter,
                FraudAlert.severity == FraudAlertSeverity.CRITICAL.value,
                FraudAlert.status.in_(unresolved_statuses),
            )
        )
        critical_result = await self.db.execute(critical_unresolved_query)
        critical_unresolved = critical_result.scalar() or 0

        high_unresolved_query = select(func.count(FraudAlert.id)).where(
            and_(
                base_filter,
                FraudAlert.severity == FraudAlertSeverity.HIGH.value,
                FraudAlert.status.in_(unresolved_statuses),
            )
        )
        high_result = await self.db.execute(high_unresolved_query)
        high_unresolved = high_result.scalar() or 0

        # Average resolution time (for resolved alerts)
        resolution_time_query = select(
            func.avg(
                func.extract(
                    "epoch",
                    FraudAlert.resolved_at - FraudAlert.created_at
                ) / 3600
            )
        ).where(
            and_(
                base_filter,
                FraudAlert.resolved_at.isnot(None),
            )
        )
        resolution_result = await self.db.execute(resolution_time_query)
        avg_resolution_hours = resolution_result.scalar()

        summary = {
            "venue_id": str(venue_id),
            "date_from": str(date_from),
            "date_to": str(date_to),
            "total_alerts": total_alerts,
            "new_alerts": by_status.get(FraudAlertStatus.NEW.value, 0),
            "investigating_alerts": by_status.get(FraudAlertStatus.INVESTIGATING.value, 0),
            "confirmed_alerts": by_status.get(FraudAlertStatus.CONFIRMED.value, 0),
            "dismissed_alerts": by_status.get(FraudAlertStatus.DISMISSED.value, 0),
            "resolved_alerts": by_status.get(FraudAlertStatus.RESOLVED.value, 0),
            "by_type": [
                {"alert_type": k, "count": v} for k, v in by_type.items()
            ],
            "by_severity": [
                {"severity": k, "count": v} for k, v in by_severity.items()
            ],
            "by_status": [
                {"status": k, "count": v} for k, v in by_status.items()
            ],
            "critical_unresolved": critical_unresolved,
            "high_unresolved": high_unresolved,
            "average_resolution_hours": (
                round(avg_resolution_hours, 2) if avg_resolution_hours else None
            ),
        }

        logger.info(
            "fraud_summary_generated",
            venue_id=str(venue_id),
            date_from=str(date_from),
            date_to=str(date_to),
            total_alerts=total_alerts,
        )

        return summary

    # =========================================================================
    # Helper Methods
    # =========================================================================

    async def _create_alert(
        self,
        venue_id: uuid.UUID,
        alert_type: str,
        severity: FraudAlertSeverity,
        title: str,
        description: str,
        detection_data: Dict[str, Any],
        entity_type: Optional[str] = None,
        entity_id: Optional[uuid.UUID] = None,
        threshold_value: Optional[Decimal] = None,
        actual_value: Optional[Decimal] = None,
    ) -> FraudAlert:
        """
        Create a new fraud alert and publish the creation event.

        This is an internal helper method used by all detection checks
        to create consistent alert records.

        Args:
            venue_id: The venue the alert belongs to.
            alert_type: Type identifier for the alert.
            severity: Severity level of the alert.
            title: Short summary title for the alert.
            description: Detailed description of the detected issue.
            detection_data: Raw data that triggered the alert.
            entity_type: Optional type of entity involved.
            entity_id: Optional ID of the entity involved.
            threshold_value: Optional threshold that was exceeded.
            actual_value: Optional actual value that triggered the alert.

        Returns:
            The newly created FraudAlert instance.
        """
        alert = FraudAlert(
            venue_id=venue_id,
            alert_type=alert_type,
            severity=severity.value,
            status=FraudAlertStatus.NEW.value,
            entity_type=entity_type,
            entity_id=entity_id,
            title=title,
            description=description,
            detection_data=detection_data,
            threshold_value=threshold_value,
            actual_value=actual_value,
        )

        self.db.add(alert)
        await self.db.commit()
        await self.db.refresh(alert)

        logger.info(
            "fraud_alert_created",
            alert_id=str(alert.id),
            venue_id=str(venue_id),
            alert_type=alert_type,
            severity=severity.value,
            entity_type=entity_type,
            entity_id=str(entity_id) if entity_id else None,
        )

        # Publish event
        if self.event_publisher:
            await self.event_publisher.publish(
                EventType.FRAUD_ALERT_CREATED,
                {
                    "alert_id": str(alert.id),
                    "venue_id": str(venue_id),
                    "alert_type": alert_type,
                    "severity": severity.value,
                    "title": title,
                    "entity_type": entity_type,
                    "entity_id": str(entity_id) if entity_id else None,
                },
                venue_id=venue_id,
            )

        return alert
